services:
  otelcol:
    image: otel/opentelemetry-collector-contrib:0.161.0@sha256:fd328de2552466ad78385e1b1289c3f2402b1c45f265b252aab1955b42845ac1
    volumes:
      - ./otelcol-config.yaml:/etc/otelcol-contrib/config.yaml
    ports:
      - "4317:4317"
      - "4318:4318"
    environment:
      - GRAFANA_CLOUD_USERNAME
      - GRAFANA_CLOUD_API_KEY
      - GRAFANA_CLOUD_ENDPOINT
